source 'https://rubygems.org'

ruby '2.2.5'

gem 'activemodel', '5.1.3'
gem 'factory_girl', '4.8.0'
gem 'rspec', '3.6.0'
gem 'rspec-virtus', '1.0.2'
gem 'sinatra', '1.4.8'
gem 'sinatra-json', '0.1.0'
gem 'shoulda-matchers', '2.7.0'
gem 'virtus', '1.0.5'
